default: &default
  adapter: mysql2
  pool: 5
  username: admin
  password: admin1234
  port: 3306
  host: mydb.cw4wnferdr5q.us-west-2.rds.amazonaws.com
  encoding: utf8
  collation: utf8_general_ci



development:
  <<: *default
  # adapter: mysql2
  database: mydb

test:
  <<: *default
  database: mydb


production:
  <<: *default
  database: mydb
